import path from "node:path"

const root = path.join(import.meta.dir, "..")
const files = [
  "tokens.css",
  "theme-base.css",
  "theme-application.css",
  "scheme-light.css",
  "scheme-dark.css",
  "density-compact.css",
]
const css = (await Promise.all(files.map((file) => Bun.file(path.join(root, "vendor/ds", file)).text()))).join("\n")
const icon = await Bun.file(path.join(root, "vendor/ds/favicon.svg")).text()
await Bun.write(
  path.join(root, "src/brand.gen.ts"),
  `// Generated by script/brand.ts from the pinned DS distribution.\nexport const appearance = ${JSON.stringify(
    {
      css: css
        .replaceAll(":root", ":host")
        .replace(/\[data-(?:theme|color-scheme|density)="[^"]+"\]/g, (selector) => `:host(${selector})`),
      favicon: `data:image/svg+xml,${encodeURIComponent(icon)}`,
    },
    null,
    2,
  )}\n`,
)
