import path from "path"
import { Context, Effect, Layer } from "effect"
import { FSUtil } from "@reddb-io/redcode-core/fs-util"
import { Ripgrep } from "@reddb-io/redcode-core/ripgrep"
import { LayerNode } from "@reddb-io/redcode-core/effect/layer-node"
import { InstanceState } from "@/effect/instance-state"

/**
 * What this project already looks like.
 *
 * A prototype is only useful if what the user sees is what they would get, and the prompt's "find
 * the design system and use it" is an instruction the model follows unevenly. So the facts are
 * gathered once and handed over: which framework, which tokens, which fonts, which pages to read.
 * Nothing is evaluated — every fact is read as text — and nothing is guessed: a fact that is not
 * in the repository is not in the summary.
 *
 * The person owns the result. A `DESIGN.md` in the project (open-design's convention) or a
 * `.red/DESIGN.md` is believed as-is and no scan runs; when neither exists the scan writes the
 * second one, and from then on editing it is how the summary is corrected.
 */

/** Looked up from the directory upward, first match wins. */
export const FILES = ["DESIGN.md", ".red/DESIGN.md"] as const
export const GENERATED = ".red/DESIGN.md"
export const HEADER = "<!-- generated by redcode design mode; edit freely, it will not be overwritten -->"

/** Enough to be a reminder, not a second system prompt. */
export const MAX_CHARS = 3_000
export const MAX_TOKENS = 40

export interface PackageJson {
  readonly dependencies?: Record<string, string>
  readonly devDependencies?: Record<string, string>
}

export interface Facts {
  /** Framework and styling libraries, as "name version" strings. */
  readonly stack: readonly string[]
  /** Where the tokens came from, relative to the directory. */
  readonly tokensFile?: string
  /** `--name: value` pairs, capped. */
  readonly tokens: readonly string[]
  readonly fonts: readonly string[]
  /** Paths the model should read before drawing. */
  readonly pages: readonly string[]
  /** A design document already in the repo: path and its first lines. */
  readonly doc?: { readonly path: string; readonly excerpt: string }
  /** Tailwind v3 config path, when one exists. */
  readonly tailwindConfig?: string
  /** shadcn's `components.json`, when one exists. */
  readonly shadcn?: string
}

const KNOWN: Record<string, string> = {
  tailwindcss: "Tailwind",
  "@kobalte/core": "Kobalte (headless components)",
  "@ark-ui/solid": "Ark UI",
  "@ark-ui/react": "Ark UI",
  "@radix-ui/react-slot": "Radix UI",
  "@radix-ui/themes": "Radix Themes",
  "@mui/material": "MUI",
  "@chakra-ui/react": "Chakra UI",
  "@mantine/core": "Mantine",
  antd: "Ant Design",
  "@headlessui/react": "Headless UI",
  "@headlessui/vue": "Headless UI",
  vuetify: "Vuetify",
  "styled-components": "styled-components",
  "@emotion/react": "Emotion",
  "@vanilla-extract/css": "vanilla-extract",
  "@stitches/react": "Stitches",
  "solid-js": "Solid",
  react: "React",
  vue: "Vue",
  svelte: "Svelte",
  "@angular/core": "Angular",
  "@solidjs/start": "SolidStart",
  next: "Next.js",
  nuxt: "Nuxt",
  "@sveltejs/kit": "SvelteKit",
  "lucide-react": "Lucide icons",
  "lucide-solid": "Lucide icons",
  "@tabler/icons-react": "Tabler icons",
  "@heroicons/react": "Heroicons",
  "@phosphor-icons/react": "Phosphor icons",
}

/** Which of the libraries we recognise the project depends on, nearest package first. */
export function stackFrom(packages: readonly PackageJson[]): string[] {
  const seen = new Map<string, string>()
  for (const pkg of packages) {
    for (const deps of [pkg.dependencies, pkg.devDependencies]) {
      for (const [name, version] of Object.entries(deps ?? {})) {
        const label = KNOWN[name]
        if (!label || seen.has(label)) continue
        const clean = version.replace(/^[\^~>=<]+/, "").trim()
        seen.set(label, /^\d/.test(clean) ? `${label} ${clean}` : label)
      }
    }
  }
  return [...seen.values()]
}

/**
 * The token declarations in a stylesheet: a `:root { --… }` block, or Tailwind v4's `@theme`.
 * Values are kept — a colour is a fact, and the model needs it verbatim.
 */
export function tokensFrom(css: string): string[] {
  const cleaned = css.replace(/\/\*[\s\S]*?\*\//g, "")
  const blocks = [...cleaned.matchAll(/(?:^|[\s}])(:root|html|@theme(?:\s+inline)?)\s*\{([^{}]*)\}/gi)].map(
    (m) => m[2] ?? "",
  )
  const out: string[] = []
  for (const block of blocks) {
    for (const decl of block.split(";")) {
      const m = /^\s*(--[\w-]+)\s*:\s*(.+?)\s*$/.exec(decl)
      if (!m) continue
      out.push(`${m[1]}: ${m[2]!.replace(/\s+/g, " ").slice(0, 80)}`)
      if (out.length >= MAX_TOKENS) return out
    }
  }
  return out
}

export function fontsFrom(css: string): string[] {
  const names = new Set<string>()
  // `font-family` in plain CSS; `--font-*` tokens in Tailwind v4 and most token files.
  for (const m of css.matchAll(/(?:font-family|--font[\w-]*)\s*:\s*([^;}]+)/gi)) {
    for (const raw of (m[1] ?? "").split(",")) {
      const name = raw.trim().replace(/^["']|["']$/g, "")
      if (
        !name ||
        /^(inherit|initial|unset|var\(|-apple-system|system-ui|ui-sans-serif|ui-serif|ui-monospace|sans-serif|serif|monospace|BlinkMacSystemFont|Segoe UI|Roboto|Helvetica|Arial)/i.test(
          name,
        )
      )
        continue
      names.add(name)
      if (names.size >= 8) return [...names]
    }
  }
  return [...names]
}

export function render(facts: Facts): string {
  const lines: string[] = []
  if (facts.stack.length) lines.push(`Stack: ${facts.stack.join(", ")}.`)
  if (facts.tailwindConfig)
    lines.push(`Tailwind config: ${facts.tailwindConfig} (read theme.extend for the palette and fonts).`)
  if (facts.shadcn) lines.push(`shadcn/ui is set up (${facts.shadcn}); use its components and CSS variables.`)
  if (facts.tokens.length) {
    lines.push("", `Tokens (${facts.tokensFile}):`, ...facts.tokens.map((t) => `- ${t}`))
  }
  if (facts.fonts.length) lines.push("", `Fonts: ${facts.fonts.join(", ")}.`)
  if (facts.pages.length)
    lines.push("", "Read these before drawing anything; match them:", ...facts.pages.map((p) => `- ${p}`))
  if (facts.doc) lines.push("", `Design notes at ${facts.doc.path}:`, "", facts.doc.excerpt.trim())
  if (lines.length === 0) {
    return "No design system was found here: no tokens, no Tailwind config, no component library. Choose one look, declare it as --tokens in :root, and keep to it."
  }
  const text = lines.join("\n")
  return text.length > MAX_CHARS ? text.slice(0, MAX_CHARS - 1) + "…" : text
}

export interface Interface {
  /** The summary the reminder injects: the person's file when there is one, the scan otherwise. */
  readonly summary: () => Effect.Effect<string>
}

export class Service extends Context.Service<Service, Interface>()("@redcode/DesignSystem") {}

const layer = Layer.effect(
  Service,
  Effect.gen(function* () {
    const fs = yield* FSUtil.Service
    const ripgrep = yield* Ripgrep.Service

    const read = (file: string) => fs.readFileStringSafe(file).pipe(Effect.orElseSucceed(() => undefined))

    // The scan runs once per instance; the file check runs every time, so an edit — or a deletion,
    // to regenerate — is seen on the next turn without restarting anything.
    const scanned = yield* InstanceState.make(
      Effect.fn("DesignSystem.scan")(function* (ctx) {
        const stop = ctx.worktree === "/" ? ctx.directory : ctx.worktree
        const cwd = stop
        const rel = (file: string) => path.relative(ctx.directory, file) || "."

        const packages: PackageJson[] = []
        for (const file of yield* fs.findUp("package.json", ctx.directory, stop).pipe(Effect.orElseSucceed(() => []))) {
          const json = yield* fs.readJson(file).pipe(Effect.orElseSucceed(() => undefined))
          if (json && typeof json === "object") packages.push(json as PackageJson)
        }

        const glob = (pattern: string, limit: number) =>
          ripgrep.glob({ cwd, pattern, limit }).pipe(
            Effect.map((entries) => entries.filter((e) => e.type === "file").map((e) => path.join(cwd, e.path))),
            Effect.orElseSucceed(() => [] as string[]),
          )

        const tailwindConfig = (yield* glob("tailwind.config.{js,cjs,mjs,ts}", 1))[0]
        const shadcn = (yield* glob("components.json", 1))[0]

        // The stylesheet with the most custom properties is the token file, wherever it lives.
        const tokenHits = yield* ripgrep
          .grep({ cwd, pattern: "(^|[{;\\s])--[\\w-]+\\s*:", include: "*.css", limit: 400 })
          .pipe(Effect.orElseSucceed(() => []))
        // A match is a line, and a token file may put many on one line, so the likeliest few
        // are read and the one with the most declarations wins.
        const counts = new Map<string, number>()
        for (const hit of tokenHits) counts.set(hit.entry.path, (counts.get(hit.entry.path) ?? 0) + 1)
        let tokensPath: string | undefined
        let tokensCss: string | undefined
        let tokens: string[] = []
        for (const [candidate] of [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 4)) {
          const css = yield* read(path.join(cwd, candidate))
          const found = css ? tokensFrom(css) : []
          if (found.length > tokens.length) {
            tokensPath = candidate
            tokensCss = css
            tokens = found
          }
        }

        const fontHits = yield* ripgrep
          .grep({ cwd, pattern: "font-family\\s*:", include: "*.css", limit: 60 })
          .pipe(Effect.orElseSucceed(() => []))
        const fonts = fontsFrom([...(tokensCss ? [tokensCss] : []), ...fontHits.map((h) => h.text)].join("\n"))

        const pages = yield* glob("**/{pages,routes,views,screens}/**/*.{tsx,jsx,vue,svelte}", 5)

        const docPath = (yield* glob("{docs/design*.md,docs/DESIGN*.md,STYLEGUIDE.md,styleguide.md}", 1))[0]
        const docText = docPath ? yield* read(docPath) : undefined
        const doc =
          docPath && docText ? { path: rel(docPath), excerpt: docText.split("\n").slice(0, 40).join("\n") } : undefined

        const facts: Facts = {
          stack: stackFrom(packages),
          ...(tokensPath ? { tokensFile: rel(path.join(cwd, tokensPath)) } : {}),
          tokens,
          fonts,
          pages: pages.map(rel),
          ...(doc ? { doc } : {}),
          ...(tailwindConfig ? { tailwindConfig: rel(tailwindConfig) } : {}),
          ...(shadcn ? { shadcn: rel(shadcn) } : {}),
        }
        return render(facts)
      }),
    )

    const summary = Effect.fn("DesignSystem.summary")(function* () {
      const ctx = yield* InstanceState.context
      const stop = ctx.worktree === "/" ? ctx.directory : ctx.worktree
      for (const name of FILES) {
        const found = yield* fs.findUp(name, ctx.directory, stop).pipe(Effect.orElseSucceed(() => []))
        const text = found[0] ? yield* read(found[0]) : undefined
        if (text?.trim()) {
          const body = text.replace(HEADER, "").trim()
          return body.length > MAX_CHARS * 2 ? body.slice(0, MAX_CHARS * 2 - 1) + "…" : body
        }
      }
      const text = yield* InstanceState.get(scanned)
      const target = path.join(ctx.directory, GENERATED)
      yield* fs.ensureDir(path.dirname(target)).pipe(Effect.ignore)
      yield* Effect.promise(() => Bun.write(target, `${HEADER}\n\n${text}\n`)).pipe(Effect.ignore)
      return text
    })

    return Service.of({ summary })
  }),
)

export const node = LayerNode.make({ service: Service, layer, deps: [FSUtil.node, Ripgrep.node] })

export * as DesignSystem from "./system"
