import { build } from "vite"
import tailwindcss from "@tailwindcss/vite"
import { readdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

// This build embeds the DS, Brand fonts and browser code into the portable Console page.
// No CDN, runtime compiler or desktop app process is needed to serve it.
const root = path.resolve(import.meta.dirname, "../console-ui")
const out = path.resolve(import.meta.dirname, "../dist/console-ui")
await build({
  configFile: false,
  root,
  base: "./",
  plugins: [tailwindcss()],
  build: {
    outDir: out,
    emptyOutDir: true,
    assetsInlineLimit: Infinity,
    minify: true,
    sourcemap: false,
  },
})
const files = await readdir(path.join(out, "assets"))
const css = await readFile(path.join(out, "assets", files.find((name) => name.endsWith(".css"))!), "utf8")
const js = await readFile(path.join(out, "assets", files.find((name) => name.endsWith(".js"))!), "utf8")
const html = (await readFile(path.join(out, "index.html"), "utf8"))
  .replace(/<link[^>]*rel="stylesheet"[^>]*>/, () => "<style>" + css + "</style>")
  .replace(
    /<script[^>]*src="[^"]*"[^>]*><\/script>/,
    () => '<script type="module">' + js.replaceAll("</script", "<\\/script") + "</script>",
  )
await writeFile(
  path.resolve(import.meta.dirname, "../src/console/page.gen.ts"),
  "// Generated by bun run build:console. Edit console-ui/ instead.\nexport const page = " +
    JSON.stringify(html) +
    "\n",
)
