export const reviewCopy = {
  title: "Design",
  params: "Params",
  paramEmpty:
    "This revision has no interactive controls. Ask the agent to expose component parameters when publishing the prototype.",
  paramScenario: "Scenario",
  paramCustom: "Custom values",
  paramReset: "Restart scenario",
  paramSelect: "Pick a component in the preview",
  paramComponent: "Component",
  paramName: "Scenario name",
  paramSave: "Save scenario",
  paramPublish: "Saving publishes a new revision with these parameters. Explore freely before saving.",
  paramLatest: "Open the latest revision before saving a scenario.",
  paramSaved: "Scenario saved in a new revision",

  details: "Details",
  feedback: "Feedback",
  tasks: "Design tasks",
  tasksEmpty: "No Design tasks recorded yet.",
  tasksUnavailable: "Design tasks could not be updated. Refresh to retry.",
  share: "Share on local network",
  shareClose: "Close",
  shareUnavailable:
    "Local network sharing is off. Run redcode service set hostname 0.0.0.0 and redcode service restart, then reopen this review.",
  shareLink: "Send this link to a colleague on the same network:",
  stateReviewing: "Applying anti-slop…",
  qualityReview: "Anti-slop review",
  runAntiSlop: "Run anti-slop",
  antiSlopFocus: "What should the review and fixes focus on? (optional)",
  antiSlopScope:
    "Audit this variant, fix the findings and publish the changes. Verify once, then stop for your review.",
  antiSlopRequested: "Anti-slop requested. Follow the audit and fixes in the conversation.",
  feedEmpty: "Replies from the agent appear here.",
  feedUnavailable: "Conversation unavailable",
  accessLost:
    "This page is no longer signed in to the review. Reload to sign in again or see how to get back in; the Design session is unaffected.",
  accessReload: "Reload",
  you: "You",
  feedNote: "note",
  feedNotes: "notes",
  feedCancelled: "cancelled",
  round: "Round",
  roundAnswered: "Answered by revision",
  endingAfterRound: "Ending after this round",
  keepReviewing: "Keep reviewing",
  stageReceived: "Received",
  stageFixing: "Fixing",
  stageStopped: "Stopped",
  stagePublished: "Published",
  stageUnverified: "Published, not verified",
  stageVerifying: "Verifying",
  stageVerifyFailed: "Verify failed",
  stageRecording: "Recording outcomes",
  stageMissing: "Outcomes missing",
  stageRecorded: "Outcomes recorded",
  stageReady: "Ready for review",
  stepOf: "Step {{step}} of 5: {{stage}}",
  detailQueued: "waiting for the agent to take them up",
  detailDelivered: "delivered to the agent",
  detailWorking: "the agent is working on them",
  detailAddressed: "{{done}} of {{count}} addressed",
  detailNotAddressed: "{{count}} not addressed",
  detailUnpublished: "every note is addressed, nothing is published yet",
  detailNotVerified: "not verified yet",
  detailChecking: "checking the notes on the latest revision",
  detailRecorded: "{{done}} of {{count}} recorded",
  detailWithout: "{{count}} without an outcome",
  countResolved: "{{count}} marked resolved",
  countPartial: "{{count}} partly fixed",
  countUnresolved: "{{count}} not fixed",
  countAccepted: "{{count}} won't fix",
  countClosed: "{{count}} closed by you",
  receivedAgo: "received {{time}} ago",
  timeSeconds: "{{count}} s",
  timeMinutes: "{{count}} min",
  timeHours: "{{count}} h",
  liveConnecting: "Connecting to the conversation…",
  liveOffline: "Offline, retrying",
  liveWorking: "Agent working",
  liveLast: "Last event {{time}} ago",
  liveTool: "Running {{tool}}",
  liveIdle: "Agent idle",
  liveIdleSince: "Agent idle since {{time}}",
  liveVerify: "Verify running · {{time}}",
  chipRevision: "R{{ordinal}}",
  chipLatest: "Latest",
  chipBehind: "{{count}} behind",
  chipUpdating: "Updating…",
  chipFailed: "Load failed",
  chipOffline: "Offline",
  chipOfflineHint: "The page lost its connection and keeps retrying; what it shows may be out of date.",
  lineLatest: "Latest, {{time}}",
  lineAnswers: "{{when}}, answers round {{round}}.",
  lineAfter: "{{when}}, published after round {{round}} was answered.",
  lineBefore: "This preview is from before round {{round}}.",
  lineWorking: "The agent is working on {{notes}}.",
  lineQueued: "The agent has not taken the notes up yet.",
  lineStopped: "The agent stopped with {{notes}} not addressed.",
  lineStoppedAll: "The agent stopped before publishing.",
  lineYours: "You published this revision while round {{round}} was open.",
  lineYoursWhy: "The agent has not answered it.",
  lineUnanswered: "This revision was published while round {{round}} was open.",
  lineUnansweredWhy: "It does not answer the round.",
  lineOlder: "An older revision, from {{time}}.",
  lineOlderWhy: "The latest is from {{time}}.",
  lineNewer: "A newer revision is ready.",
  lineCard: "Your open note belongs to this one.",
  lineCardAction: "Add note and switch",
  linePending: "Send or discard your message first.",
  linePendingAction: "Retry sending",
  discardPending: "Discard message",
  reloadResend: "Reload and resend",
  discarded: "Message discarded",
  lineFailed: "The latest revision failed to load. Still showing {{name}}.",
  lineFailedAction: "Retry",
  lineSwitched: "Switched to the revision published {{time}} ago.",
  dialogNewer: "A newer revision is ready. Close this dialog to switch to it.",
  roundRange: "Rounds {{first}} to {{last}}",
  roundsEarlier: "{{count}} earlier rounds",
  noteCount: "{{count}} notes",
  noteCountOne: "1 note",
  leftCount: "{{count}} left",
  leftOf: "{{left}} of {{count}} left",
  nothingLeft: "nothing left",
  hiddenCount: "{{count}} hidden",
  onlyLeft: "Only what is left",
  statusRefused: "Status recording refused",
  rowAgent: "Agent",
  notVerified: "not verified yet",
  noteWaiting: "The agent has not reported a change yet.",
  closeByHand: "Close by hand…",
  revealMissing: "That element is not in the revision on screen.",
  agentReply: "Agent",
  replyMore: "Show more",
  replyLess: "Show less",
  activity: "Activity",
  activityCount: "{{count}} entries",
  activityCountOne: "1 entry",
  activityFailed: "{{count}} failed",
  tasksDone: "{{done}} of {{total}} done",
  statusOpen: "Open",
  statusAddressed: "Fixed, not verified yet",
  statusResolved: "Resolved",
  statusPartial: "Partial",
  statusUnresolved: "Unresolved",
  statusAccepted: "Won't fix",
  resend: "Send again",
  resendQueued: "Note queued for the next round",
  verified: "Verified round",
  verifiedOn: "on revision",
  verifyPass: "found, no findings",
  verifyWarn: "found with findings",
  verifyFail: "missing or blocked",
  openReport: "Open captures",
  resentFrom: "Re-sent from round",
  roundOpen: "Add a note to Send & end while earlier notes are open; the review then ends after this round.",
  endRefused: "The review was not ended; the notes were sent without ending. Record the open notes to end it.",
  recordAs: "Record as",
  recordAccepted: "Accepted (won't fix)",
  recordUnresolved: "Unresolved",
  recordReason: "Reason",
  record: "Record",
  recordReasonRequired: "Write a reason before recording.",
  recorded: "Note recorded",
  byReviewer: "recorded by you",
  approvalScreenshot: "Include the current preview as a visual reference for Plan",
  capturing: "Capturing the approved preview…",
  screenshotUnavailable: "Preview screenshot unavailable; Plan continues with the recorded design decisions.",
  approvalOpenNotes: "Notes without a recorded outcome:",
  approvalRecordAll: "Record the open notes as accepted by the reviewer and approve",
  approvalReviewNotes: "Notes the agent did not resolve; read them before approving:",
  create: "Create design",
  name: "Name",
  journey: "Starting point",
  new: "New interface",
  existing: "Existing application",
  application: "Application directory",
  engine: "Preview engine",
  designTarget: "Design for",
  targetWeb: "Web (responsive)",
  targetApp: "Mobile app",
  targetPresentation: "Presentation",
  designPlatform: "Platform",
  platformBoth: "iOS and Android",
  platformIos: "iOS",
  platformAndroid: "Android",
  objective: "What should this interface accomplish?",
  audience: "Audience",
  constraints: "Constraints",
  references: "References (one per line)",
  review: "Review",
  history: "Revision",
  restore: "Restore as new revision",
  restoreConfirm: "Restore {{revision}} as a new revision? It becomes the latest revision of this design.",
  restoreBusy: "The agent is working. Restore once it is idle, so its next revision does not replace yours.",
  platformHint: "The agent designs and audits for this platform. The phone frame above only previews.",
  approve: "Approve this revision",
  evidence: "Review evidence",
  noAudit: "This revision has no completed audit. Approval will record this gap.",
  confirm: "Approve this revision and continue in Plan?",
  reopen: "Reopen review",
  notes: "Message to the agent",
  messageHint: "A message for the agent. To note an element, select it in the preview.",
  target: "Selected element",
  send: "Send to agent",
  sendEnd: "Send & end",
  sendHint: "Ctrl+Enter sends to the agent",
  cardNote: "Note for this element",
  cardHint: "Enter adds the note · Shift+Enter for a new line · Ctrl+Enter sends",
  closeCard: "Close note",
  cardMoved: "Note moved to",
  reveal: "Reveal",
  dismiss: "Dismiss",
  queueFixes: "Queue selected fixes",
  inboxEmpty: "Nothing to report for this revision.",
  severityWarn: "Warning",
  severityInfo: "Info",
  inboxQueued: "Queued",
  inboxResolved: "Resolved",
  draft: "Draft saved on this device",
  received: "Feedback received",
  sending: "Sending feedback to the agent…",
  feedbackSaved: "Feedback saved on this device. Retry to send it to the agent.",
  feedbackFailed: "Feedback was not sent. Your draft is saved on this device.",
  retry: "Retry sending saved feedback",
  refresh: "Refresh",
  more: "More actions",
  latest: "Show the latest revision",
  annotate: "Annotate elements",
  remove: "Remove",
  add: "Add note",
  attachment: "Attach image or SVG",
  assets: "Assets",
  export: "Export",
  html: "Portable HTML",
  gif: "SVG to GIF",
  audit: "Check scenarios and accessibility",
  jobs: "Exports and checks",
  cancel: "Cancel",
  download: "Download",
  duration: "Seconds",
  fps: "Frames per second",
  size: "Longest edge (px)",
  transparent: "Transparent background",
  source: "SVG source",
  waiting: "Waiting for a published revision",
  system: "Design system",
  refreshSystem: "Refresh source evidence",
  decisions: "Decisions",
  questions: "Open questions",
  scenarios: "Scenarios",
  none: "None recorded",
  tweaks: "Adjust tokens",
  token: "CSS custom property",
  value: "Value",
  apply: "Apply and publish",
  reset: "Reset adjustments",
  width: "Preview width",
  full: "Fit panel",
  busy: "Working…",
  done: "Done",
  refreshed: "Preview refreshed",
  approved: "Design approved. Continue in the terminal to review the implementation plan.",
  approveAction: "Approve and continue in Plan",
  approvalScope:
    "Your selected direction, decisions and acceptance criteria will be recorded with this revision. Product implementation still requires plan approval in the terminal.",
  approvalWhole: "Entire revision (no variant selected)",
  approvalDetails: "View approved decisions",
  variants: "Variants",
  variant: "Variant",
  screens: "Screens",
  single: "Single view",
  sideBySide: "Side by side",
  compareVariant: "Compare variant",
  addVariant: "Add variant",
  variantPrompt: "What should the new variant explore?",
  variantHint: "The agent will add an alternative to this design and publish a new revision in this conversation.",
  requestVariant: "Request variant",
  variantRequested: "Variant requested. The agent will publish a new revision here.",
  noVariants: "This revision has no separate variants.",
  loadingRevision: "Loading the revision…",
  loadingQueued: "Waiting for the preview build…",
  loadingTools: "Preparing design tools (first use only)…",
  loadingBuild: "Building the preview…",
  loadingAssets: "Loading assets and fonts…",
  loadingRuntime: "Starting the preview…",
  loadingElapsed: "{{seconds}} s",
  zeroRevision: "The agent is preparing the first revision…",
  agentWaiting: "Waiting for the agent to start",
  agentThinking: "The agent is thinking…",
  agentTool: "The agent is running {{tool}}…",
  agentCompacting: "The agent is compacting its context…",
  agentRetrying: "A model request failed; retrying in {{time}}",
  agentRetryingNow: "A model request failed; retrying now",
  agentPermission: "Waiting for your approval in the terminal",
  agentFailed: "The agent stopped with an error",
  agentInterrupted: "The agent was interrupted",
  interruptUser: "by you",
  interruptShutdown: "by a shutdown",
  interruptSuperseded: "by a newer run",
  interruptInactivity: "after inactivity",
  previewFailed: "The preview could not be built.",
  previewRetry: "Retry",
  organizeVariants: "Separate existing variants",
  organizeRequested: "Asked the agent to separate this prototype into selectable variants.",
  variantActions: "Variant actions",
  renameVariant: "Rename…",
  splitVariant: "Split…",
  deleteVariant: "Delete…",
  deleteVariantTab: "Delete variant",
  moveLeft: "Move left",
  moveRight: "Move right",
  selectMerge: "Select variants to merge",
  mergeVariants: "Merge…",
  mergeSelection: "Variants to merge",
  mergeNeedsTwo: "Select at least two variants to merge.",
  renameHeading: "Rename variant",
  renameLabel: "New name",
  renameAction: "Rename",
  renameSame: "Type a different name to rename this variant.",
  splitHeading: "Split variant",
  splitHint: "The agent keeps this variant's id on one half and adds a new variant for the other.",
  splitAction: "Split",
  mergeHeading: "Merge variants",
  mergeHint: "The agent keeps the first selected variant and removes the others.",
  mergeAction: "Merge",
  deleteHeading: "Delete variant?",
  deleteHint:
    "The agent removes this variant with its scenarios, controls and presets in a new revision. Earlier revisions keep it.",
  deleteAction: "Delete",
  operationGuidance: "Guidance for the agent (optional)",
  operationApplying: "Applying…",
  operationMerging: "Merging…",
  operationSplitting: "Splitting…",
  operationRequested: "Variant change sent. The agent will publish a new revision here.",
  operationFailed: "The variant change was not applied:",
  operationUnchanged: "The agent published a revision without this variant change.",
  operationStopped: "The agent stopped without publishing this variant change.",
  operationRetry: "Retry variant change",
  noteOrphaned: "Variant removed",
  retarget: "Retarget to",
  approvalReselect: "The approved variant is not in this revision. Select a variant before approving again.",
  mobile: "Mobile · 390 px",
  tablet: "Tablet · 768 px",
  desktop: "Desktop · 1440 px",
  iphone: "iPhone · 393 px",
  android: "Android · 412 px",
  slide: "Slide · 1920 px",
  devicePlatform: "Phone frame",
  present: "Present",
  presentTitle: "Presentation",
  presenterView: "Presenter view",
  audienceView: "Audience window",
  presentPrevious: "Previous slide",
  presentNext: "Next slide",
  presentUpNext: "Up next",
  presentEnd: "End of the deck",
  presentNotes: "Speaker notes",
  presentNoNotes: "No notes for this slide.",
  presentElapsed: "Elapsed",
  presentReset: "Reset timer",
  presentFullscreen: "Full screen",
  presentHint: "F full screen · ← → move · P presenter view",
  presentEmpty: "This design has no published revision to present yet.",
  presentSyncPaused: "Sync paused — press a key to resume",
  presentLoading: "Loading the deck…",
  slides: "Slides",
  pdf: "Slides to PDF",
  feedbackRequired: "Write a note before sending feedback.",
  failure: "The request failed. Your draft has been preserved.",
  published: "Revision published",
  closed: "This review has ended.",
  diagram: "Diagram or selected content",
  alternatives: "Other designs",
  noAssets: "Import an image or SVG to begin.",
  compare: "Compare with approved design",
  implementation: "Built application directory",
  findings: "Layout observations",
  sourceCurrent: "Matches refreshed evidence",
  sourceChanged: "Source changed or removed; publish an updated revision",
  whiteboard: "Open diagram whiteboard",
  close: "Close whiteboard",
  annotateShort: "Annotate",
  annotateShortcut: "Annotate elements (A)",
} as const
export type ReviewCopy = { [Key in keyof typeof reviewCopy]: string }
