export const reviewCopy = {
  title: "Design",
  params: "Params",
  paramEmpty:
    "This revision has no interactive controls. Ask the agent to expose component parameters when publishing the prototype.",
  paramScenario: "Scenario",
  paramCustom: "Custom values",
  paramReset: "Restart scenario",
  paramSelect: "Pick a component in the preview",
  paramComponent: "Component",
  paramName: "Scenario name",
  paramSave: "Save scenario",
  paramPublish: "Saving publishes a new revision with these parameters. Explore freely before saving.",
  paramLatest: "Open the latest revision before saving a scenario.",
  paramSaved: "Scenario saved in a new revision",

  details: "Details",
  conversation: "Conversation",
  stateWorking: "Agent working…",
  stateIdle: "Idle",
  statePublished: "New revision published",
  feedEmpty: "Replies from the agent appear here.",
  feedUnavailable: "Conversation unavailable",
  you: "You",
  feedNote: "note",
  feedNotes: "notes",
  rounds: "Feedback rounds",
  round: "Round",
  roundAwaiting: "awaiting a revision",
  roundAnswered: "answered by",
  statusOpen: "Open",
  statusResolved: "Resolved",
  statusPartial: "Partial",
  statusUnresolved: "Unresolved",
  statusAccepted: "Won't fix",
  resend: "Send again",
  resendQueued: "Note queued for the next round",
  verified: "Verified round",
  verifiedOn: "on revision",
  verifyPass: "found, no findings",
  verifyWarn: "found with findings",
  verifyFail: "missing or blocked",
  openReport: "Open captures",
  resentFrom: "Re-sent from round",
  roundOpen: "Send & end waits until every note of the open rounds has a recorded outcome.",
  endRefused: "The review was not ended; the notes were sent without ending. Record the open notes to end it.",
  recordAs: "Record as",
  recordAccepted: "Accepted (won't fix)",
  recordUnresolved: "Unresolved",
  recordReason: "Reason",
  record: "Record",
  recordReasonRequired: "Write a reason before recording.",
  recorded: "Note recorded",
  byReviewer: "recorded by you",
  approvalOpenNotes: "Notes without a recorded outcome:",
  approvalRecordAll: "Record the open notes as accepted by the reviewer and approve",
  approvalReviewNotes: "Notes the agent did not resolve; read them before approving:",
  create: "Create design",
  name: "Name",
  journey: "Starting point",
  new: "New interface",
  existing: "Existing application",
  application: "Application directory",
  engine: "Preview engine",
  designTarget: "Design for",
  targetWeb: "Web (responsive)",
  targetApp: "Mobile app",
  targetPresentation: "Presentation",
  designPlatform: "Platform",
  platformBoth: "iOS and Android",
  platformIos: "iOS",
  platformAndroid: "Android",
  objective: "What should this interface accomplish?",
  audience: "Audience",
  constraints: "Constraints",
  references: "References (one per line)",
  review: "Review",
  history: "Revision",
  restore: "Restore as new revision",
  approve: "Approve this revision",
  evidence: "Review evidence",
  noAudit: "This revision has no completed audit. Approval will record this gap.",
  confirm: "Approve this revision and continue in Plan?",
  reopen: "Reopen review",
  notes: "Review notes",
  target: "Selected element",
  send: "Send to agent",
  sendEnd: "Send & end",
  sendHint: "Ctrl+Enter sends to the agent",
  cardNote: "Note for this element",
  cardHint: "Enter adds the note · Shift+Enter for a new line · Ctrl+Enter sends",
  closeCard: "Close note",
  cardMoved: "Note moved to",
  reveal: "Reveal",
  dismiss: "Dismiss",
  queueFixes: "Queue selected fixes",
  inboxEmpty: "Nothing to report for this revision.",
  severityWarn: "Warning",
  severityInfo: "Info",
  inboxQueued: "Queued",
  inboxResolved: "Resolved",
  draft: "Draft saved on this device",
  received: "Feedback received",
  retry: "Retry sending saved feedback",
  refresh: "Refresh",
  more: "More actions",
  latest: "New revision available",
  annotate: "Annotate elements",
  inspect: "Select an element or text in the preview to attach a note.",
  remove: "Remove",
  add: "Add note",
  attachment: "Attach image or SVG",
  assets: "Assets",
  export: "Export",
  html: "Portable HTML",
  gif: "SVG to GIF",
  audit: "Check scenarios and accessibility",
  jobs: "Exports and checks",
  cancel: "Cancel",
  download: "Download",
  duration: "Seconds",
  fps: "Frames per second",
  size: "Longest edge (px)",
  transparent: "Transparent background",
  source: "SVG source",
  waiting: "Waiting for a published revision",
  system: "Design system",
  refreshSystem: "Refresh source evidence",
  decisions: "Decisions",
  questions: "Open questions",
  scenarios: "Scenarios",
  none: "None recorded",
  tweaks: "Adjust tokens",
  token: "CSS custom property",
  value: "Value",
  apply: "Apply and publish",
  reset: "Reset adjustments",
  width: "Preview width",
  full: "Fit panel",
  busy: "Working…",
  done: "Done",
  refreshed: "Preview refreshed",
  approved: "Design approved. Continue in the terminal to review the implementation plan.",
  approveAction: "Approve and continue in Plan",
  approvalScope:
    "Your selected direction, decisions and acceptance criteria will be recorded with this revision. Product implementation still requires plan approval in the terminal.",
  approvalWhole: "Entire revision (no variant selected)",
  approvalDetails: "View approved decisions",
  variants: "Variants",
  variant: "Variant",
  screens: "Screens",
  single: "Single view",
  sideBySide: "Side by side",
  compareVariant: "Compare variant",
  addVariant: "Add variant",
  variantPrompt: "What should the new variant explore?",
  variantHint: "The agent will add an alternative to this design and publish a new revision in this conversation.",
  requestVariant: "Request variant",
  variantRequested: "Variant requested. The agent will publish a new revision here.",
  noVariants: "This revision has no separate variants.",
  organizeVariants: "Separate existing variants",
  organizeRequested: "Asked the agent to separate this prototype into selectable variants.",
  variantActions: "Variant actions",
  renameVariant: "Rename…",
  splitVariant: "Split…",
  deleteVariant: "Delete…",
  moveLeft: "Move left",
  moveRight: "Move right",
  selectMerge: "Select variants to merge",
  mergeVariants: "Merge…",
  mergeSelection: "Variants to merge",
  mergeNeedsTwo: "Select at least two variants to merge.",
  renameHeading: "Rename variant",
  renameLabel: "New name",
  renameAction: "Rename",
  renameSame: "Type a different name to rename this variant.",
  splitHeading: "Split variant",
  splitHint: "The agent keeps this variant's id on one half and adds a new variant for the other.",
  splitAction: "Split",
  mergeHeading: "Merge variants",
  mergeHint: "The agent keeps the first selected variant and removes the others.",
  mergeAction: "Merge",
  deleteHeading: "Delete variant?",
  deleteHint:
    "The agent removes this variant with its scenarios, controls and presets in a new revision. Earlier revisions keep it.",
  deleteAction: "Delete",
  operationGuidance: "Guidance for the agent (optional)",
  operationApplying: "Applying…",
  operationMerging: "Merging…",
  operationSplitting: "Splitting…",
  operationRequested: "Variant change sent. The agent will publish a new revision here.",
  operationFailed: "The variant change was not applied:",
  operationUnchanged: "The agent published a revision without this variant change.",
  operationStopped: "The agent stopped without publishing this variant change.",
  operationRetry: "Retry variant change",
  noteOrphaned: "Variant removed",
  retarget: "Retarget to",
  approvalReselect: "The approved variant is not in this revision. Select a variant before approving again.",
  mobile: "Mobile · 390 px",
  tablet: "Tablet · 768 px",
  desktop: "Desktop · 1440 px",
  iphone: "iPhone · 393 px",
  android: "Android · 412 px",
  slide: "Slide · 1920 px",
  devicePlatform: "Phone frame",
  present: "Present",
  presentTitle: "Presentation",
  presenterView: "Presenter view",
  audienceView: "Audience window",
  presentPrevious: "Previous slide",
  presentNext: "Next slide",
  presentUpNext: "Up next",
  presentEnd: "End of the deck",
  presentNotes: "Speaker notes",
  presentNoNotes: "No notes for this slide.",
  presentElapsed: "Elapsed",
  presentReset: "Reset timer",
  presentFullscreen: "Full screen",
  presentHint: "F full screen · ← → move · P presenter view",
  presentEmpty: "This design has no published revision to present yet.",
  slides: "Slides",
  pdf: "Slides to PDF",
  feedbackRequired: "Write a note before sending feedback.",
  failure: "The request failed. Your draft has been preserved.",
  published: "Revision published",
  closed: "This review has ended.",
  diagram: "Diagram or selected content",
  alternatives: "Other designs",
  noAssets: "Import an image or SVG to begin.",
  compare: "Compare with approved design",
  implementation: "Built application directory",
  findings: "Layout observations",
  sourceCurrent: "Matches refreshed evidence",
  sourceChanged: "Source changed or removed; publish an updated revision",
  whiteboard: "Open diagram whiteboard",
  close: "Close whiteboard",
  annotateShort: "Annotate",
  annotateShortcut: "Annotate elements (A)",
} as const
export type ReviewCopy = { [Key in keyof typeof reviewCopy]: string }
