export * as DesignManifest from "./manifest.js"

import path from "node:path"
import { Design } from "@opencode/schema/design"
import { DesignFiles } from "./files.js"
import type { DesignReferences } from "./references.js"

export const FILE = ".red/DESIGN.md"
export const START = "<!-- redcode:design-system:start -->"
export const END = "<!-- redcode:design-system:end -->"
export const NOTES = "<!-- redcode:notes -->"

export interface Input {
  readonly stack: readonly string[]
  readonly tokens: readonly string[]
  readonly roots: readonly string[]
  readonly inventory: readonly Design.Component[]
  readonly references?: readonly DesignReferences.Reference[]
}

export type Result =
  | { readonly status: "created" | "updated" | "unchanged" }
  | { readonly status: "kept"; readonly reason: string }

/**
 * Creates the manifest when the application has none and, on refresh, rewrites only the marked
 * block when it changed. Everything outside the markers is the user's: a manifest without markers,
 * or with damaged ones, is kept untouched and the reason is reported.
 */
export async function write(application: string, input: Input, refresh: boolean): Promise<Result> {
  const file = path.join(application, FILE)
  const existing = (await Bun.file(file).exists()) ? await Bun.file(file).text() : undefined
  if (existing === undefined) {
    await DesignFiles.atomic(file, render(input))
    return { status: "created" }
  }
  if (!refresh) return { status: "unchanged" }
  const starts = existing.split(START).length - 1
  const ends = existing.split(END).length - 1
  if (starts === 0 && ends === 0) return { status: "kept", reason: "user-authored, no generated markers" }
  if (starts !== 1 || ends !== 1)
    return { status: "kept", reason: "generated markers are duplicated or incomplete; repair or remove them" }
  const start = existing.indexOf(START)
  const end = existing.indexOf(END)
  if (end < start) return { status: "kept", reason: "generated end marker precedes the start marker; repair it" }
  const eol = existing.includes("\r\n") ? "\r\n" : "\n"
  const block = generated(input).replaceAll("\n", eol)
  if (existing.slice(start, end + END.length) === block) return { status: "unchanged" }
  await DesignFiles.atomic(file, existing.slice(0, start) + block + existing.slice(end + END.length))
  return { status: "updated" }
}

export const render = (input: Input) =>
  [
    "# Design system",
    "",
    generated(input),
    "",
    "## Notes",
    NOTES,
    "",
    "Conventions the files do not show: spacing rhythm, voice, what must not be reused. This section survives refresh.",
    "",
  ].join("\n")

function generated(input: Input) {
  return [
    START,
    "_Generated by redcode Design mode from the project's files. Edit anything outside these markers; `design_document refresh` rewrites the block between them._",
    "",
    "## Stack",
    ...input.stack.map((line) => `- ${line}`),
    "",
    "## Tokens",
    ...(input.tokens.length
      ? input.tokens.map((file) => `- ${file}`)
      : ["- None found: no tokens, theme or global stylesheet under src."]),
    "",
    "## Components",
    ...(input.roots.length
      ? input.roots.flatMap((root) => [
          `### ${root}`,
          ...input.inventory
            .filter((entry) => entry.root === root)
            .map((entry) => `- ${entry.name} (${entry.file}${entry.props ? `, ${entry.props}` : ""})`),
          "",
        ])
      : ["- No component root: no src/components, src/design-system or rendering packages/*/src index was found.", ""]),
    ...(input.references?.length
      ? [
          "## Source references",
          "_Inferred, not authoritative. CSS token names cover the observed discovery excerpt (up to 12,000 bytes and 100 names per file); component names cover the bounded inventory. SHA-256 hashes identify whole source files. Refresh after source changes; read project guidance before choosing a semantic role._",
          "",
          ...input.references.flatMap((reference) => [
            `### ${reference.file}`,
            `SHA-256: ${reference.hash}`,
            ...reference.tokens.map((token) => `- ${token.name} (${reference.file}:${token.line})`),
            ...(reference.components.length ? [`Exports: ${reference.components.join(", ")}`] : []),
            "",
          ]),
        ]
      : []),
    END,
  ].join("\n")
}
