export * as DesignManifest from "./manifest"

import path from "node:path"
import { Design } from "@reddb-io/redcode-schema/design"
import { DesignFiles } from "./files"

export const FILE = ".red/DESIGN.md"
export const START = "<!-- redcode:design-system:start -->"
export const END = "<!-- redcode:design-system:end -->"
export const NOTES = "<!-- redcode:notes -->"

export interface Input {
  readonly stack: readonly string[]
  readonly tokens: readonly string[]
  readonly roots: readonly string[]
  readonly inventory: readonly Design.Component[]
}

/**
 * Creates the manifest when the application has none and, on refresh, rewrites only the marked
 * block. Everything outside the markers is the user's, so a manifest without markers is never touched.
 */
export async function write(application: string, input: Input, refresh: boolean) {
  const file = path.join(application, FILE)
  const existing = (await Bun.file(file).exists()) ? await Bun.file(file).text() : undefined
  if (existing === undefined) {
    await DesignFiles.atomic(file, render(input))
    return true
  }
  if (!refresh) return false
  const start = existing.indexOf(START)
  const end = existing.indexOf(END, start)
  if (start < 0 || end < 0) return false
  await DesignFiles.atomic(file, existing.slice(0, start) + generated(input) + existing.slice(end + END.length))
  return true
}

export const render = (input: Input) =>
  [
    "# Design system",
    "",
    generated(input),
    "",
    "## Notes",
    NOTES,
    "",
    "Conventions the files do not show: spacing rhythm, voice, what must not be reused. This section survives refresh.",
    "",
  ].join("\n")

function generated(input: Input) {
  const roots = input.roots.length ? input.roots : [...new Set(input.inventory.map((entry) => entry.root))]
  return [
    START,
    "_Generated by redcode Design mode from the project's files. Edit anything outside these markers; `design_document refresh` rewrites the block between them._",
    "",
    "## Stack",
    ...input.stack.map((line) => `- ${line}`),
    "",
    "## Tokens",
    ...(input.tokens.length
      ? input.tokens.map((file) => `- ${file}`)
      : ["- None found: no tokens, theme or global stylesheet under src."]),
    "",
    "## Components",
    ...(roots.length
      ? roots.flatMap((root) => {
          const entries = input.inventory.filter((entry) => entry.root === root)
          return [
            `### ${root}`,
            ...(entries.length
              ? entries.map((entry) => `- ${entry.name} (${entry.file}${entry.props ? `, ${entry.props}` : ""})`)
              : ["- No exported PascalCase components found."]),
            "",
          ]
        })
      : ["- No component root: no src/components, src/design-system or packages/*/src index was found.", ""]),
    END,
  ].join("\n")
}
