// Generated by @reddb-io/redcode-httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint2_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.agent"]) => ({ list: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint3_0Input = {
  readonly workspace?: Endpoint3_0Request["query"]["workspace"]
  readonly limit?: Endpoint3_0Request["query"]["limit"]
  readonly order?: Endpoint3_0Request["query"]["order"]
  readonly search?: Endpoint3_0Request["query"]["search"]
  readonly directory?: Endpoint3_0Request["query"]["directory"]
  readonly project?: Endpoint3_0Request["query"]["project"]
  readonly subpath?: Endpoint3_0Request["query"]["subpath"]
  readonly cursor?: Endpoint3_0Request["query"]["cursor"]
}
const Endpoint3_0 = (raw: RawClient["server.session"]) => (input?: Endpoint3_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint3_1Input = {
  readonly id?: Endpoint3_1Request["payload"]["id"]
  readonly agent?: Endpoint3_1Request["payload"]["agent"]
  readonly model?: Endpoint3_1Request["payload"]["model"]
  readonly location?: Endpoint3_1Request["payload"]["location"]
}
const Endpoint3_1 = (raw: RawClient["server.session"]) => (input?: Endpoint3_1Input) =>
  raw["session.create"]({
    payload: { id: input?.["id"], agent: input?.["agent"], model: input?.["model"], location: input?.["location"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint3_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint3_3Input = { readonly sessionID: Endpoint3_3Request["params"]["sessionID"] }
const Endpoint3_3 = (raw: RawClient["server.session"]) => (input: Endpoint3_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_4Request = Parameters<RawClient["server.session"]["session.goal"]>[0]
type Endpoint3_4Input = { readonly sessionID: Endpoint3_4Request["params"]["sessionID"] }
const Endpoint3_4 = (raw: RawClient["server.session"]) => (input: Endpoint3_4Input) =>
  raw["session.goal"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_5Request = Parameters<RawClient["server.session"]["session.goalSet"]>[0]
type Endpoint3_5Input = {
  readonly sessionID: Endpoint3_5Request["params"]["sessionID"]
  readonly objective: Endpoint3_5Request["payload"]["objective"]
  readonly criteria?: Endpoint3_5Request["payload"]["criteria"]
  readonly gates?: Endpoint3_5Request["payload"]["gates"]
  readonly maxTurns?: Endpoint3_5Request["payload"]["maxTurns"]
  readonly agent?: Endpoint3_5Request["payload"]["agent"]
  readonly model?: Endpoint3_5Request["payload"]["model"]
  readonly stopAfter?: Endpoint3_5Request["payload"]["stopAfter"]
  readonly executePlan?: Endpoint3_5Request["payload"]["executePlan"]
}
const Endpoint3_5 = (raw: RawClient["server.session"]) => (input: Endpoint3_5Input) =>
  raw["session.goalSet"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      objective: input["objective"],
      criteria: input["criteria"],
      gates: input["gates"],
      maxTurns: input["maxTurns"],
      agent: input["agent"],
      model: input["model"],
      stopAfter: input["stopAfter"],
      executePlan: input["executePlan"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_6Request = Parameters<RawClient["server.session"]["session.goalControl"]>[0]
type Endpoint3_6Input = {
  readonly sessionID: Endpoint3_6Request["params"]["sessionID"]
  readonly action: Endpoint3_6Request["payload"]["action"]
  readonly maxTurns?: Endpoint3_6Request["payload"]["maxTurns"]
}
const Endpoint3_6 = (raw: RawClient["server.session"]) => (input: Endpoint3_6Input) =>
  raw["session.goalControl"]({
    params: { sessionID: input["sessionID"] },
    payload: { action: input["action"], maxTurns: input["maxTurns"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_7Request = Parameters<RawClient["server.session"]["session.plans"]>[0]
type Endpoint3_7Input = { readonly sessionID: Endpoint3_7Request["params"]["sessionID"] }
const Endpoint3_7 = (raw: RawClient["server.session"]) => (input: Endpoint3_7Input) =>
  raw["session.plans"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_8Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint3_8Input = {
  readonly sessionID: Endpoint3_8Request["params"]["sessionID"]
  readonly agent: Endpoint3_8Request["payload"]["agent"]
}
const Endpoint3_8 = (raw: RawClient["server.session"]) => (input: Endpoint3_8Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_9Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint3_9Input = {
  readonly sessionID: Endpoint3_9Request["params"]["sessionID"]
  readonly model: Endpoint3_9Request["payload"]["model"]
}
const Endpoint3_9 = (raw: RawClient["server.session"]) => (input: Endpoint3_9Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_10Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint3_10Input = {
  readonly sessionID: Endpoint3_10Request["params"]["sessionID"]
  readonly id?: Endpoint3_10Request["payload"]["id"]
  readonly prompt: Endpoint3_10Request["payload"]["prompt"]
  readonly delivery?: Endpoint3_10Request["payload"]["delivery"]
  readonly resume?: Endpoint3_10Request["payload"]["resume"]
}
const Endpoint3_10 = (raw: RawClient["server.session"]) => (input: Endpoint3_10Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], prompt: input["prompt"], delivery: input["delivery"], resume: input["resume"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_11Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint3_11Input = { readonly sessionID: Endpoint3_11Request["params"]["sessionID"] }
const Endpoint3_11 = (raw: RawClient["server.session"]) => (input: Endpoint3_11Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_12Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint3_12Input = { readonly sessionID: Endpoint3_12Request["params"]["sessionID"] }
const Endpoint3_12 = (raw: RawClient["server.session"]) => (input: Endpoint3_12Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_13Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint3_13Input = {
  readonly sessionID: Endpoint3_13Request["params"]["sessionID"]
  readonly messageID: Endpoint3_13Request["payload"]["messageID"]
  readonly files?: Endpoint3_13Request["payload"]["files"]
}
const Endpoint3_13 = (raw: RawClient["server.session"]) => (input: Endpoint3_13Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_14Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint3_14Input = { readonly sessionID: Endpoint3_14Request["params"]["sessionID"] }
const Endpoint3_14 = (raw: RawClient["server.session"]) => (input: Endpoint3_14Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_15Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint3_15Input = { readonly sessionID: Endpoint3_15Request["params"]["sessionID"] }
const Endpoint3_15 = (raw: RawClient["server.session"]) => (input: Endpoint3_15Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_16Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint3_16Input = { readonly sessionID: Endpoint3_16Request["params"]["sessionID"] }
const Endpoint3_16 = (raw: RawClient["server.session"]) => (input: Endpoint3_16Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_17Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint3_17Input = {
  readonly sessionID: Endpoint3_17Request["params"]["sessionID"]
  readonly limit?: Endpoint3_17Request["query"]["limit"]
  readonly after?: Endpoint3_17Request["query"]["after"]
}
const Endpoint3_17 = (raw: RawClient["server.session"]) => (input: Endpoint3_17Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_18Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint3_18Input = {
  readonly sessionID: Endpoint3_18Request["params"]["sessionID"]
  readonly after?: Endpoint3_18Request["query"]["after"]
}
const Endpoint3_18 = (raw: RawClient["server.session"]) => (input: Endpoint3_18Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint3_19Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint3_19Input = { readonly sessionID: Endpoint3_19Request["params"]["sessionID"] }
const Endpoint3_19 = (raw: RawClient["server.session"]) => (input: Endpoint3_19Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_20Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint3_20Input = {
  readonly sessionID: Endpoint3_20Request["params"]["sessionID"]
  readonly messageID: Endpoint3_20Request["params"]["messageID"]
}
const Endpoint3_20 = (raw: RawClient["server.session"]) => (input: Endpoint3_20Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup3 = (raw: RawClient["server.session"]) => ({
  list: Endpoint3_0(raw),
  create: Endpoint3_1(raw),
  active: Endpoint3_2(raw),
  get: Endpoint3_3(raw),
  goal: Endpoint3_4(raw),
  goalSet: Endpoint3_5(raw),
  goalControl: Endpoint3_6(raw),
  plans: Endpoint3_7(raw),
  switchAgent: Endpoint3_8(raw),
  switchModel: Endpoint3_9(raw),
  prompt: Endpoint3_10(raw),
  compact: Endpoint3_11(raw),
  wait: Endpoint3_12(raw),
  stage: Endpoint3_13(raw),
  clear: Endpoint3_14(raw),
  commit: Endpoint3_15(raw),
  context: Endpoint3_16(raw),
  history: Endpoint3_17(raw),
  events: Endpoint3_18(raw),
  interrupt: Endpoint3_19(raw),
  message: Endpoint3_20(raw),
})

type Endpoint4_0Request = Parameters<RawClient["server.design"]["design.review"]>[0]
type Endpoint4_0Input = { readonly sessionID: Endpoint4_0Request["params"]["sessionID"] }
const Endpoint4_0 = (raw: RawClient["server.design"]) => (input: Endpoint4_0Input) =>
  raw["design.review"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_1Request = Parameters<RawClient["server.design"]["design.whiteboard"]>[0]
type Endpoint4_1Input = { readonly sessionID: Endpoint4_1Request["params"]["sessionID"] }
const Endpoint4_1 = (raw: RawClient["server.design"]) => (input: Endpoint4_1Input) =>
  raw["design.whiteboard"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_2Request = Parameters<RawClient["server.design"]["design.list"]>[0]
type Endpoint4_2Input = { readonly sessionID: Endpoint4_2Request["params"]["sessionID"] }
const Endpoint4_2 = (raw: RawClient["server.design"]) => (input: Endpoint4_2Input) =>
  raw["design.list"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_3Request = Parameters<RawClient["server.design"]["design.create"]>[0]
type Endpoint4_3Input = {
  readonly sessionID: Endpoint4_3Request["params"]["sessionID"]
  readonly name: Endpoint4_3Request["payload"]["name"]
  readonly journey: Endpoint4_3Request["payload"]["journey"]
  readonly engine: Endpoint4_3Request["payload"]["engine"]
  readonly kind: Endpoint4_3Request["payload"]["kind"]
  readonly application?: Endpoint4_3Request["payload"]["application"]
}
const Endpoint4_3 = (raw: RawClient["server.design"]) => (input: Endpoint4_3Input) =>
  raw["design.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      name: input["name"],
      journey: input["journey"],
      engine: input["engine"],
      kind: input["kind"],
      application: input["application"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_4Request = Parameters<RawClient["server.design"]["design.get"]>[0]
type Endpoint4_4Input = {
  readonly sessionID: Endpoint4_4Request["params"]["sessionID"]
  readonly designID: Endpoint4_4Request["params"]["designID"]
}
const Endpoint4_4 = (raw: RawClient["server.design"]) => (input: Endpoint4_4Input) =>
  raw["design.get"]({ params: { sessionID: input["sessionID"], designID: input["designID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_5Request = Parameters<RawClient["server.design"]["design.update"]>[0]
type Endpoint4_5Input = {
  readonly sessionID: Endpoint4_5Request["params"]["sessionID"]
  readonly designID: Endpoint4_5Request["params"]["designID"]
  readonly controls?: Endpoint4_5Request["payload"]["controls"]
  readonly presets?: Endpoint4_5Request["payload"]["presets"]
  readonly name?: Endpoint4_5Request["payload"]["name"]
  readonly brief?: Endpoint4_5Request["payload"]["brief"]
  readonly decisions?: Endpoint4_5Request["payload"]["decisions"]
  readonly questions?: Endpoint4_5Request["payload"]["questions"]
  readonly scenarios?: Endpoint4_5Request["payload"]["scenarios"]
  readonly designSystem?: Endpoint4_5Request["payload"]["designSystem"]
  readonly entry?: Endpoint4_5Request["payload"]["entry"]
  readonly tweaks?: Endpoint4_5Request["payload"]["tweaks"]
}
const Endpoint4_5 = (raw: RawClient["server.design"]) => (input: Endpoint4_5Input) =>
  raw["design.update"]({
    params: { sessionID: input["sessionID"], designID: input["designID"] },
    payload: {
      controls: input["controls"],
      presets: input["presets"],
      name: input["name"],
      brief: input["brief"],
      decisions: input["decisions"],
      questions: input["questions"],
      scenarios: input["scenarios"],
      designSystem: input["designSystem"],
      entry: input["entry"],
      tweaks: input["tweaks"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_6Request = Parameters<RawClient["server.design"]["design.revisions"]>[0]
type Endpoint4_6Input = {
  readonly sessionID: Endpoint4_6Request["params"]["sessionID"]
  readonly designID: Endpoint4_6Request["params"]["designID"]
}
const Endpoint4_6 = (raw: RawClient["server.design"]) => (input: Endpoint4_6Input) =>
  raw["design.revisions"]({ params: { sessionID: input["sessionID"], designID: input["designID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_7Request = Parameters<RawClient["server.design"]["design.preview"]>[0]
type Endpoint4_7Input = {
  readonly sessionID: Endpoint4_7Request["params"]["sessionID"]
  readonly designID: Endpoint4_7Request["params"]["designID"]
  readonly revisionID: Endpoint4_7Request["params"]["revisionID"]
}
const Endpoint4_7 = (raw: RawClient["server.design"]) => (input: Endpoint4_7Input) =>
  raw["design.preview"]({
    params: { sessionID: input["sessionID"], designID: input["designID"], revisionID: input["revisionID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_8Request = Parameters<RawClient["server.design"]["design.publish"]>[0]
type Endpoint4_8Input = {
  readonly sessionID: Endpoint4_8Request["params"]["sessionID"]
  readonly designID: Endpoint4_8Request["params"]["designID"]
  readonly name: Endpoint4_8Request["payload"]["name"]
}
const Endpoint4_8 = (raw: RawClient["server.design"]) => (input: Endpoint4_8Input) =>
  raw["design.publish"]({
    params: { sessionID: input["sessionID"], designID: input["designID"] },
    payload: { name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_9Request = Parameters<RawClient["server.design"]["design.restore"]>[0]
type Endpoint4_9Input = {
  readonly sessionID: Endpoint4_9Request["params"]["sessionID"]
  readonly designID: Endpoint4_9Request["params"]["designID"]
  readonly revision: Endpoint4_9Request["payload"]["revision"]
}
const Endpoint4_9 = (raw: RawClient["server.design"]) => (input: Endpoint4_9Input) =>
  raw["design.restore"]({
    params: { sessionID: input["sessionID"], designID: input["designID"] },
    payload: { revision: input["revision"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_10Request = Parameters<RawClient["server.design"]["design.reopen"]>[0]
type Endpoint4_10Input = {
  readonly sessionID: Endpoint4_10Request["params"]["sessionID"]
  readonly designID: Endpoint4_10Request["params"]["designID"]
}
const Endpoint4_10 = (raw: RawClient["server.design"]) => (input: Endpoint4_10Input) =>
  raw["design.reopen"]({ params: { sessionID: input["sessionID"], designID: input["designID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_11Request = Parameters<RawClient["server.design"]["design.refresh"]>[0]
type Endpoint4_11Input = {
  readonly sessionID: Endpoint4_11Request["params"]["sessionID"]
  readonly designID: Endpoint4_11Request["params"]["designID"]
}
const Endpoint4_11 = (raw: RawClient["server.design"]) => (input: Endpoint4_11Input) =>
  raw["design.refresh"]({ params: { sessionID: input["sessionID"], designID: input["designID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_12Request = Parameters<RawClient["server.design"]["design.feedback"]>[0]
type Endpoint4_12Input = {
  readonly sessionID: Endpoint4_12Request["params"]["sessionID"]
  readonly designID: Endpoint4_12Request["params"]["designID"]
  readonly params?: Endpoint4_12Request["payload"]["params"]
  readonly id: Endpoint4_12Request["payload"]["id"]
  readonly revision: Endpoint4_12Request["payload"]["revision"]
  readonly text: Endpoint4_12Request["payload"]["text"]
  readonly items: Endpoint4_12Request["payload"]["items"]
  readonly assets: Endpoint4_12Request["payload"]["assets"]
  readonly snapshot: Endpoint4_12Request["payload"]["snapshot"]
  readonly whiteboards?: Endpoint4_12Request["payload"]["whiteboards"]
  readonly delivery: Endpoint4_12Request["payload"]["delivery"]
  readonly end: Endpoint4_12Request["payload"]["end"]
}
const Endpoint4_12 = (raw: RawClient["server.design"]) => (input: Endpoint4_12Input) =>
  raw["design.feedback"]({
    params: { sessionID: input["sessionID"], designID: input["designID"] },
    payload: {
      params: input["params"],
      id: input["id"],
      revision: input["revision"],
      text: input["text"],
      items: input["items"],
      assets: input["assets"],
      snapshot: input["snapshot"],
      whiteboards: input["whiteboards"],
      delivery: input["delivery"],
      end: input["end"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_13Request = Parameters<RawClient["server.design"]["design.approve"]>[0]
type Endpoint4_13Input = {
  readonly sessionID: Endpoint4_13Request["params"]["sessionID"]
  readonly designID: Endpoint4_13Request["params"]["designID"]
  readonly revision: Endpoint4_13Request["payload"]["revision"]
  readonly variant?: Endpoint4_13Request["payload"]["variant"]
}
const Endpoint4_13 = (raw: RawClient["server.design"]) => (input: Endpoint4_13Input) =>
  raw["design.approve"]({
    params: { sessionID: input["sessionID"], designID: input["designID"] },
    payload: { revision: input["revision"], variant: input["variant"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_14Request = Parameters<RawClient["server.design"]["design.approval"]>[0]
type Endpoint4_14Input = {
  readonly sessionID: Endpoint4_14Request["params"]["sessionID"]
  readonly designID: Endpoint4_14Request["params"]["designID"]
  readonly revisionID: Endpoint4_14Request["params"]["revisionID"]
}
const Endpoint4_14 = (raw: RawClient["server.design"]) => (input: Endpoint4_14Input) =>
  raw["design.approval"]({
    params: { sessionID: input["sessionID"], designID: input["designID"], revisionID: input["revisionID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_15Request = Parameters<RawClient["server.design"]["design.assets"]>[0]
type Endpoint4_15Input = {
  readonly sessionID: Endpoint4_15Request["params"]["sessionID"]
  readonly designID: Endpoint4_15Request["params"]["designID"]
}
const Endpoint4_15 = (raw: RawClient["server.design"]) => (input: Endpoint4_15Input) =>
  raw["design.assets"]({ params: { sessionID: input["sessionID"], designID: input["designID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_16Request = Parameters<RawClient["server.design"]["design.importAsset"]>[0]
type Endpoint4_16Input = {
  readonly sessionID: Endpoint4_16Request["params"]["sessionID"]
  readonly designID: Endpoint4_16Request["params"]["designID"]
  readonly name: Endpoint4_16Request["payload"]["name"]
  readonly mime: Endpoint4_16Request["payload"]["mime"]
  readonly data: Endpoint4_16Request["payload"]["data"]
  readonly source: Endpoint4_16Request["payload"]["source"]
  readonly parent?: Endpoint4_16Request["payload"]["parent"]
}
const Endpoint4_16 = (raw: RawClient["server.design"]) => (input: Endpoint4_16Input) =>
  raw["design.importAsset"]({
    params: { sessionID: input["sessionID"], designID: input["designID"] },
    payload: {
      name: input["name"],
      mime: input["mime"],
      data: input["data"],
      source: input["source"],
      parent: input["parent"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_17Request = Parameters<RawClient["server.design"]["design.jobs"]>[0]
type Endpoint4_17Input = {
  readonly sessionID: Endpoint4_17Request["params"]["sessionID"]
  readonly designID: Endpoint4_17Request["params"]["designID"]
}
const Endpoint4_17 = (raw: RawClient["server.design"]) => (input: Endpoint4_17Input) =>
  raw["design.jobs"]({ params: { sessionID: input["sessionID"], designID: input["designID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_18Request = Parameters<RawClient["server.design"]["design.render"]>[0]
type Endpoint4_18Input = {
  readonly sessionID: Endpoint4_18Request["params"]["sessionID"]
  readonly designID: Endpoint4_18Request["params"]["designID"]
  readonly revision: Endpoint4_18Request["payload"]["revision"]
  readonly format: Endpoint4_18Request["payload"]["format"]
  readonly implementation?: Endpoint4_18Request["payload"]["implementation"]
  readonly candidate?: Endpoint4_18Request["payload"]["candidate"]
  readonly asset?: Endpoint4_18Request["payload"]["asset"]
  readonly duration?: Endpoint4_18Request["payload"]["duration"]
  readonly fps?: Endpoint4_18Request["payload"]["fps"]
  readonly size?: Endpoint4_18Request["payload"]["size"]
  readonly repeat?: Endpoint4_18Request["payload"]["repeat"]
  readonly background?: Endpoint4_18Request["payload"]["background"]
  readonly transparent?: Endpoint4_18Request["payload"]["transparent"]
}
const Endpoint4_18 = (raw: RawClient["server.design"]) => (input: Endpoint4_18Input) =>
  raw["design.render"]({
    params: { sessionID: input["sessionID"], designID: input["designID"] },
    payload: {
      revision: input["revision"],
      format: input["format"],
      implementation: input["implementation"],
      candidate: input["candidate"],
      asset: input["asset"],
      duration: input["duration"],
      fps: input["fps"],
      size: input["size"],
      repeat: input["repeat"],
      background: input["background"],
      transparent: input["transparent"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_19Request = Parameters<RawClient["server.design"]["design.cancel"]>[0]
type Endpoint4_19Input = {
  readonly sessionID: Endpoint4_19Request["params"]["sessionID"]
  readonly designID: Endpoint4_19Request["params"]["designID"]
  readonly jobID: Endpoint4_19Request["params"]["jobID"]
}
const Endpoint4_19 = (raw: RawClient["server.design"]) => (input: Endpoint4_19Input) =>
  raw["design.cancel"]({
    params: { sessionID: input["sessionID"], designID: input["designID"], jobID: input["jobID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_20Request = Parameters<RawClient["server.design"]["design.download"]>[0]
type Endpoint4_20Input = {
  readonly sessionID: Endpoint4_20Request["params"]["sessionID"]
  readonly designID: Endpoint4_20Request["params"]["designID"]
  readonly jobID: Endpoint4_20Request["params"]["jobID"]
}
const Endpoint4_20 = (raw: RawClient["server.design"]) => (input: Endpoint4_20Input) =>
  raw["design.download"]({
    params: { sessionID: input["sessionID"], designID: input["designID"], jobID: input["jobID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_21Request = Parameters<RawClient["server.design"]["design.assetFile"]>[0]
type Endpoint4_21Input = {
  readonly sessionID: Endpoint4_21Request["params"]["sessionID"]
  readonly designID: Endpoint4_21Request["params"]["designID"]
  readonly assetID: Endpoint4_21Request["params"]["assetID"]
}
const Endpoint4_21 = (raw: RawClient["server.design"]) => (input: Endpoint4_21Input) =>
  raw["design.assetFile"]({
    params: { sessionID: input["sessionID"], designID: input["designID"], assetID: input["assetID"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup4 = (raw: RawClient["server.design"]) => ({
  review: Endpoint4_0(raw),
  whiteboard: Endpoint4_1(raw),
  list: Endpoint4_2(raw),
  create: Endpoint4_3(raw),
  get: Endpoint4_4(raw),
  update: Endpoint4_5(raw),
  revisions: Endpoint4_6(raw),
  preview: Endpoint4_7(raw),
  publish: Endpoint4_8(raw),
  restore: Endpoint4_9(raw),
  reopen: Endpoint4_10(raw),
  refresh: Endpoint4_11(raw),
  feedback: Endpoint4_12(raw),
  approve: Endpoint4_13(raw),
  approval: Endpoint4_14(raw),
  assets: Endpoint4_15(raw),
  importAsset: Endpoint4_16(raw),
  jobs: Endpoint4_17(raw),
  render: Endpoint4_18(raw),
  cancel: Endpoint4_19(raw),
  download: Endpoint4_20(raw),
  assetFile: Endpoint4_21(raw),
})

type Endpoint5_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint5_0Input = {
  readonly sessionID: Endpoint5_0Request["params"]["sessionID"]
  readonly limit?: Endpoint5_0Request["query"]["limit"]
  readonly order?: Endpoint5_0Request["query"]["order"]
  readonly cursor?: Endpoint5_0Request["query"]["cursor"]
}
const Endpoint5_0 = (raw: RawClient["server.message"]) => (input: Endpoint5_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.message"]) => ({ list: Endpoint5_0(raw) })

type Endpoint6_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint6_0Input = { readonly location?: Endpoint6_0Request["query"]["location"] }
const Endpoint6_0 = (raw: RawClient["server.model"]) => (input?: Endpoint6_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup6 = (raw: RawClient["server.model"]) => ({ list: Endpoint6_0(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint7_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint7_1Input = {
  readonly providerID: Endpoint7_1Request["params"]["providerID"]
  readonly location?: Endpoint7_1Request["query"]["location"]
}
const Endpoint7_1 = (raw: RawClient["server.provider"]) => (input: Endpoint7_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup7 = (raw: RawClient["server.provider"]) => ({ list: Endpoint7_0(raw), get: Endpoint7_1(raw) })

type Endpoint8_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint8_0Input = { readonly location?: Endpoint8_0Request["query"]["location"] }
const Endpoint8_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint8_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint8_1Input = {
  readonly integrationID: Endpoint8_1Request["params"]["integrationID"]
  readonly location?: Endpoint8_1Request["query"]["location"]
}
const Endpoint8_1 = (raw: RawClient["server.integration"]) => (input: Endpoint8_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint8_2Input = {
  readonly integrationID: Endpoint8_2Request["params"]["integrationID"]
  readonly location?: Endpoint8_2Request["query"]["location"]
  readonly key: Endpoint8_2Request["payload"]["key"]
  readonly label?: Endpoint8_2Request["payload"]["label"]
}
const Endpoint8_2 = (raw: RawClient["server.integration"]) => (input: Endpoint8_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint8_3Input = {
  readonly integrationID: Endpoint8_3Request["params"]["integrationID"]
  readonly location?: Endpoint8_3Request["query"]["location"]
  readonly methodID: Endpoint8_3Request["payload"]["methodID"]
  readonly inputs: Endpoint8_3Request["payload"]["inputs"]
  readonly label?: Endpoint8_3Request["payload"]["label"]
}
const Endpoint8_3 = (raw: RawClient["server.integration"]) => (input: Endpoint8_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint8_4Input = {
  readonly attemptID: Endpoint8_4Request["params"]["attemptID"]
  readonly location?: Endpoint8_4Request["query"]["location"]
}
const Endpoint8_4 = (raw: RawClient["server.integration"]) => (input: Endpoint8_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint8_5Input = {
  readonly attemptID: Endpoint8_5Request["params"]["attemptID"]
  readonly location?: Endpoint8_5Request["query"]["location"]
  readonly code?: Endpoint8_5Request["payload"]["code"]
}
const Endpoint8_5 = (raw: RawClient["server.integration"]) => (input: Endpoint8_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint8_6Input = {
  readonly attemptID: Endpoint8_6Request["params"]["attemptID"]
  readonly location?: Endpoint8_6Request["query"]["location"]
}
const Endpoint8_6 = (raw: RawClient["server.integration"]) => (input: Endpoint8_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint8_0(raw),
  get: Endpoint8_1(raw),
  connectKey: Endpoint8_2(raw),
  connectOauth: Endpoint8_3(raw),
  attemptStatus: Endpoint8_4(raw),
  attemptComplete: Endpoint8_5(raw),
  attemptCancel: Endpoint8_6(raw),
})

type Endpoint9_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint9_0Input = {
  readonly credentialID: Endpoint9_0Request["params"]["credentialID"]
  readonly location?: Endpoint9_0Request["query"]["location"]
  readonly label: Endpoint9_0Request["payload"]["label"]
}
const Endpoint9_0 = (raw: RawClient["server.credential"]) => (input: Endpoint9_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint9_1Input = {
  readonly credentialID: Endpoint9_1Request["params"]["credentialID"]
  readonly location?: Endpoint9_1Request["query"]["location"]
}
const Endpoint9_1 = (raw: RawClient["server.credential"]) => (input: Endpoint9_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.credential"]) => ({ update: Endpoint9_0(raw), remove: Endpoint9_1(raw) })

type Endpoint10_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
const Endpoint10_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint10_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint10_1Input = { readonly projectID?: Endpoint10_1Request["query"]["projectID"] }
const Endpoint10_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint10_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint10_2Input = { readonly id: Endpoint10_2Request["params"]["id"] }
const Endpoint10_2 = (raw: RawClient["server.permission"]) => (input: Endpoint10_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint10_3Input = {
  readonly sessionID: Endpoint10_3Request["params"]["sessionID"]
  readonly id?: Endpoint10_3Request["payload"]["id"]
  readonly action: Endpoint10_3Request["payload"]["action"]
  readonly resources: Endpoint10_3Request["payload"]["resources"]
  readonly save?: Endpoint10_3Request["payload"]["save"]
  readonly metadata?: Endpoint10_3Request["payload"]["metadata"]
  readonly source?: Endpoint10_3Request["payload"]["source"]
  readonly agent?: Endpoint10_3Request["payload"]["agent"]
}
const Endpoint10_3 = (raw: RawClient["server.permission"]) => (input: Endpoint10_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint10_4Input = { readonly sessionID: Endpoint10_4Request["params"]["sessionID"] }
const Endpoint10_4 = (raw: RawClient["server.permission"]) => (input: Endpoint10_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint10_5Input = {
  readonly sessionID: Endpoint10_5Request["params"]["sessionID"]
  readonly requestID: Endpoint10_5Request["params"]["requestID"]
}
const Endpoint10_5 = (raw: RawClient["server.permission"]) => (input: Endpoint10_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint10_6Input = {
  readonly sessionID: Endpoint10_6Request["params"]["sessionID"]
  readonly requestID: Endpoint10_6Request["params"]["requestID"]
  readonly reply: Endpoint10_6Request["payload"]["reply"]
  readonly message?: Endpoint10_6Request["payload"]["message"]
}
const Endpoint10_6 = (raw: RawClient["server.permission"]) => (input: Endpoint10_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint10_0(raw),
  listSaved: Endpoint10_1(raw),
  removeSaved: Endpoint10_2(raw),
  create: Endpoint10_3(raw),
  list: Endpoint10_4(raw),
  get: Endpoint10_5(raw),
  reply: Endpoint10_6(raw),
})

type Endpoint11_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint11_0Input = {
  readonly location?: Endpoint11_0Request["query"]["location"]
  readonly path?: Endpoint11_0Request["query"]["path"]
}
const Endpoint11_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint11_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint11_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint11_1Input = {
  readonly location?: Endpoint11_1Request["query"]["location"]
  readonly query: Endpoint11_1Request["query"]["query"]
  readonly type?: Endpoint11_1Request["query"]["type"]
  readonly limit?: Endpoint11_1Request["query"]["limit"]
}
const Endpoint11_1 = (raw: RawClient["server.fs"]) => (input: Endpoint11_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.fs"]) => ({ list: Endpoint11_0(raw), find: Endpoint11_1(raw) })

type Endpoint12_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
const Endpoint12_0 = (raw: RawClient["server.command"]) => (input?: Endpoint12_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup12 = (raw: RawClient["server.command"]) => ({ list: Endpoint12_0(raw) })

type Endpoint13_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint13_0Input = { readonly location?: Endpoint13_0Request["query"]["location"] }
const Endpoint13_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint13_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup13 = (raw: RawClient["server.skill"]) => ({ list: Endpoint13_0(raw) })

const Endpoint14_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup14 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint14_0(raw) })

type Endpoint15_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
const Endpoint15_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint15_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint15_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint15_1Input = {
  readonly location?: Endpoint15_1Request["query"]["location"]
  readonly command?: Endpoint15_1Request["payload"]["command"]
  readonly args?: Endpoint15_1Request["payload"]["args"]
  readonly cwd?: Endpoint15_1Request["payload"]["cwd"]
  readonly title?: Endpoint15_1Request["payload"]["title"]
  readonly env?: Endpoint15_1Request["payload"]["env"]
}
const Endpoint15_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint15_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint15_2Input = {
  readonly ptyID: Endpoint15_2Request["params"]["ptyID"]
  readonly location?: Endpoint15_2Request["query"]["location"]
}
const Endpoint15_2 = (raw: RawClient["server.pty"]) => (input: Endpoint15_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint15_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint15_3Input = {
  readonly ptyID: Endpoint15_3Request["params"]["ptyID"]
  readonly location?: Endpoint15_3Request["query"]["location"]
  readonly title?: Endpoint15_3Request["payload"]["title"]
  readonly size?: Endpoint15_3Request["payload"]["size"]
}
const Endpoint15_3 = (raw: RawClient["server.pty"]) => (input: Endpoint15_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint15_4Input = {
  readonly ptyID: Endpoint15_4Request["params"]["ptyID"]
  readonly location?: Endpoint15_4Request["query"]["location"]
}
const Endpoint15_4 = (raw: RawClient["server.pty"]) => (input: Endpoint15_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup15 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint15_0(raw),
  create: Endpoint15_1(raw),
  get: Endpoint15_2(raw),
  update: Endpoint15_3(raw),
  remove: Endpoint15_4(raw),
})

type Endpoint16_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
const Endpoint16_0 = (raw: RawClient["server.question"]) => (input?: Endpoint16_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint16_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint16_1Input = { readonly sessionID: Endpoint16_1Request["params"]["sessionID"] }
const Endpoint16_1 = (raw: RawClient["server.question"]) => (input: Endpoint16_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint16_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint16_2Input = {
  readonly sessionID: Endpoint16_2Request["params"]["sessionID"]
  readonly requestID: Endpoint16_2Request["params"]["requestID"]
  readonly answers: Endpoint16_2Request["payload"]["answers"]
}
const Endpoint16_2 = (raw: RawClient["server.question"]) => (input: Endpoint16_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint16_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint16_3Input = {
  readonly sessionID: Endpoint16_3Request["params"]["sessionID"]
  readonly requestID: Endpoint16_3Request["params"]["requestID"]
}
const Endpoint16_3 = (raw: RawClient["server.question"]) => (input: Endpoint16_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup16 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint16_0(raw),
  list: Endpoint16_1(raw),
  reply: Endpoint16_2(raw),
  reject: Endpoint16_3(raw),
})

type Endpoint17_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint17_0Input = { readonly location?: Endpoint17_0Request["query"]["location"] }
const Endpoint17_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint17_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup17 = (raw: RawClient["server.reference"]) => ({ list: Endpoint17_0(raw) })

type Endpoint18_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint18_0Input = {
  readonly projectID: Endpoint18_0Request["params"]["projectID"]
  readonly location?: Endpoint18_0Request["query"]["location"]
  readonly strategy: Endpoint18_0Request["payload"]["strategy"]
  readonly directory: Endpoint18_0Request["payload"]["directory"]
  readonly name?: Endpoint18_0Request["payload"]["name"]
}
const Endpoint18_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint18_1Input = {
  readonly projectID: Endpoint18_1Request["params"]["projectID"]
  readonly location?: Endpoint18_1Request["query"]["location"]
  readonly directory: Endpoint18_1Request["payload"]["directory"]
  readonly force: Endpoint18_1Request["payload"]["force"]
}
const Endpoint18_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint18_2Input = {
  readonly projectID: Endpoint18_2Request["params"]["projectID"]
  readonly location?: Endpoint18_2Request["query"]["location"]
}
const Endpoint18_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup18 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint18_0(raw),
  remove: Endpoint18_1(raw),
  refresh: Endpoint18_2(raw),
})

type Endpoint19_0Request = Parameters<RawClient["server.hook"]["hook.status"]>[0]
type Endpoint19_0Input = { readonly location?: Endpoint19_0Request["query"]["location"] }
const Endpoint19_0 = (raw: RawClient["server.hook"]) => (input?: Endpoint19_0Input) =>
  raw["hook.status"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_1Request = Parameters<RawClient["server.hook"]["hook.trust"]>[0]
type Endpoint19_1Input = { readonly location?: Endpoint19_1Request["query"]["location"] }
const Endpoint19_1 = (raw: RawClient["server.hook"]) => (input?: Endpoint19_1Input) =>
  raw["hook.trust"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_2Request = Parameters<RawClient["server.hook"]["hook.revoke"]>[0]
type Endpoint19_2Input = { readonly location?: Endpoint19_2Request["query"]["location"] }
const Endpoint19_2 = (raw: RawClient["server.hook"]) => (input?: Endpoint19_2Input) =>
  raw["hook.revoke"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_3Request = Parameters<RawClient["server.hook"]["hook.import"]>[0]
type Endpoint19_3Input = { readonly location?: Endpoint19_3Request["query"]["location"] }
const Endpoint19_3 = (raw: RawClient["server.hook"]) => (input?: Endpoint19_3Input) =>
  raw["hook.import"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup19 = (raw: RawClient["server.hook"]) => ({
  status: Endpoint19_0(raw),
  trust: Endpoint19_1(raw),
  revoke: Endpoint19_2(raw),
  import: Endpoint19_3(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  agents: adaptGroup2(raw["server.agent"]),
  sessions: adaptGroup3(raw["server.session"]),
  designs: adaptGroup4(raw["server.design"]),
  messages: adaptGroup5(raw["server.message"]),
  models: adaptGroup6(raw["server.model"]),
  providers: adaptGroup7(raw["server.provider"]),
  integrations: adaptGroup8(raw["server.integration"]),
  credentials: adaptGroup9(raw["server.credential"]),
  permissions: adaptGroup10(raw["server.permission"]),
  files: adaptGroup11(raw["server.fs"]),
  commands: adaptGroup12(raw["server.command"]),
  skills: adaptGroup13(raw["server.skill"]),
  events: adaptGroup14(raw["server.event"]),
  ptys: adaptGroup15(raw["server.pty"]),
  questions: adaptGroup16(raw["server.question"]),
  references: adaptGroup17(raw["server.reference"]),
  projectCopies: adaptGroup18(raw["server.projectCopy"]),
  hooks: adaptGroup19(raw["server.hook"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
