#!/usr/bin/env bun
// Vendors the pinned reddb-io/design-system release with the design system's own Sync.
// Usage: bun scripts/sync-design-system.ts [/path/to/design-system]
//
// The Sync reads design-system.manifest.json, enforces Kit and Layer routing for the `redcode` consumer and lands
// the release as the `@reddb-io/design-system` workspace package, which every Redcode surface consumes:
// - the GUI imports its contracts, Logo modules, Color Layer, styles and platform icons;
// - the core design app gets one shadow-root stylesheet and the favicon, generated into its brand.gen.ts.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

const root = resolve(import.meta.dir, "..")
const source = resolve(process.argv[2] ?? join(root, "../design-system"))
const manifest = JSON.parse(readFileSync(join(root, "design-system.manifest.json"), "utf8")) as {
  version: string
  dest: string
}
const dest = join(root, manifest.dest)

// The producer that runs is the checkout's, so it must be the pinned release's own.
const pinned = (await Bun.$`git -C ${source} rev-parse ${manifest.version}^{commit}`.text()).trim()
if ((await Bun.$`git -C ${source} rev-parse HEAD`.text()).trim() !== pinned)
  throw new Error(`Check out ${manifest.version} in ${source} before synchronizing`)

await Bun.$`bun ${join(source, "scripts/producer/src/cli.ts")}`.cwd(root)

// The Sync does not route the Assets Contract's platform icons yet, so they are taken byte-for-byte from the same tag.
const platform = JSON.parse(
  await Bun.$`git -C ${source} show ${manifest.version}:packages/assets/dist/platform-manifest.json`.text(),
) as { icons: { file: string }[] }
mkdirSync(join(dest, "platform"), { recursive: true })
writeFileSync(join(dest, "platform/platform-manifest.json"), JSON.stringify(platform, null, 2) + "\n")
for (const icon of platform.icons)
  writeFileSync(
    join(dest, "platform", icon.file),
    new Uint8Array(await Bun.$`git -C ${source} show ${manifest.version}:packages/assets/dist/platform/${icon.file}`.arrayBuffer()),
  )

// Local Divergence: the Kits are Svelte and Redcode renders with Solid, so the package exports their framework-free
// modules and depends only on what those import. Re-applied after every Sync, which rewrites package.json.
const contracts = (kit: string) =>
  Array.from(new Bun.Glob("**/*.variants.ts").scanSync(join(dest, "kits", kit, "src"))).map((file) => ({
    name: file.split(/[\\/]/).at(-1)!.replace(".variants.ts", ""),
    path: `./kits/${kit}/src/${file.replaceAll("\\", "/")}`,
  }))
const pkg = JSON.parse(readFileSync(join(dest, "package.json"), "utf8"))
writeFileSync(
  join(dest, "package.json"),
  JSON.stringify(
    {
      ...pkg,
      exports: {
        "./color": pkg.exports["./color"],
        "./styles/application.css": pkg.exports["./styles/application.css"],
        "./contracts/*": "./kits/base/src/*.variants.ts",
        ...Object.fromEntries(contracts("app").map((contract) => [`./contracts/${contract.name}`, contract.path])),
        "./logo/*": "./kits/base/src/logo.*.ts",
        "./platform/*": "./platform/*",
      },
      dependencies: { "tailwind-variants": pkg.dependencies["tailwind-variants"] },
      peerDependencies: undefined,
      peerDependenciesMeta: undefined,
    },
    null,
    2,
  ) + "\n",
)

// The design app injects its UI into a shadow root, so it takes the Application direction, both Color Schemes and
// the compact Density as one stylesheet (every DS appearance artifact also matches `:host`).
const css = ["tokens/tokens.css", "theme/theme-base.css", "theme/theme-application.css", "theme/scheme-light.css", "theme/scheme-dark.css", "tokens/density-compact.css"]
  .map((file) => readFileSync(join(dest, file), "utf8").replaceAll("\r\n", "\n"))
  .join("\n")
const favicon = `data:image/svg+xml,${encodeURIComponent(readFileSync(join(dest, "platform/favicon.svg"), "utf8").replaceAll("\r\n", "\n"))}`
writeFileSync(
  join(root, "packages/core/src/design/ui/brand.gen.ts"),
  `// Generated by scripts/sync-design-system.ts from @reddb-io/design-system ${manifest.version}.\nexport const appearance = ${JSON.stringify({ css, favicon }, null, 2)}\n`,
)
console.log(`Synced ${manifest.version} into ${manifest.dest}; regenerated the design app's brand.gen.ts`)
